title: Daveads
email: the.daveads@gmail.com
description: Daveads personal site
baseurl: "" # the subpath of your site, e.g. /blog

url: "https://daveads.github.io"

twitter_username: The_Daveads
github_username:  Daveads

logo: "/images/daveads.png"

# Build settings
theme: minima
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-archives
  - jekyll-admin
  - jekyll-seo-tag




url: https://daveads.github.io 

css_class: 'highlight'

google_analytics: G-BFJF15HTKT

lang_direction: "ltr"

color: "#abe123"

language: "en"

#sass:
#    load_paths:
#        - _sass
#        - node_modules
        
disqus:

#destination: public
#source: src

collections:
  tags:
    output: true
    permalink: tags/:path/

  categories:
    output: true
    permalink: categories/:path/
    
#https://github.com/rouge-ruby/rouge
markdown: kramdown
highlighter: rouge

kramdown:
  input: GFM
  

# Archives
jekyll-archives:
  enabled: [year]
  layout: archive
  permalinks:
    year: '/archives/year/:year/'


permalink: '/writing/:title/'
post_dirs: false

#defaults:  

jekyll_compose:
  default_front_matter:
    posts:
      layout: post
      title:
      date:
      categories:
      tags:

exclude:
   - .sass-cache/
   - .jekyll-cache/
   - gemfiles/
   - Gemfile.lock
   - node_modules/
   - vendor/bundle/
   - vendor/cache/
   - vendor/gems/
   - vendor/ruby/
